// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Broker is an autogenerated mock type for the Broker type
type Broker struct {
	mock.Mock
}

// GetStockQueueName provides a mock function with given fields:
func (_m *Broker) GetStockQueueName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Publish provides a mock function with given fields: key, msg
func (_m *Broker) Publish(key string, msg []byte) error {
	ret := _m.Called(key, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(key, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
